rl_runner:
  training_time_min: 29

model_registry:
  remote_path: s3://popiol-crypto-models
  maturity_levels_day: [1, 3, 9, 27, 81, 243]
  max_models_per_level: 8
  archive_retention_days: 7
  local_path: data/models
  local_retention_days: 60

data_registry:
  quotes_remote_path: s3://popiol-crypto/kraken
  quotes_local_path: data/quotes
  config_remote_path: s3://popiol-crypto/config
  retention_days: 21
  trainset_remote_path: s3://popiol-crypto/trainset
  trainset_keys_remote_path: s3://popiol-crypto/trainset_keys
  trainset_keys_local_path: data/trainset_keys

agent_builder:
  n_agents: 1
  name_list_file: data/names.csv

data_transformer:
  memory_length: 10
  expected_daily_change: 0.02
  float_precision: 32

portfolio_manager:
  init_cash: 1000
  transaction_fee: 0.005
  expiration_time_sec: 5400
  min_transaction: 15

trainset:
  local_path: data/trainset

evolution_handler:
  max_n_params: 1000000

evolution_randomizer:
  new_basic_model_prob: 0.1
  merge_prob: 0.2
  dependent_prob: 0.5
  remove_layer_prob: 0.005
  add_dense_prob: 0.005
  add_conv_prob: 0.02
  add_dropout_prob: 0.005
  resize_prob: 0.01
  relu_prob: 0.01
  reuse_prob: 0.005
  select_weight: 1
  multiply_weight: 0.5
  dot_weight: 0.5
  transform_weight: 1
  concat_weight: 1
  serial_weight: 1
  learn_on_success_weight: 1
  learn_on_mistake_weight: 0
  learn_on_both_weight: 1
  learn_on_extreme_weight: 1

reports:
  aggregated_path: data/aggregated
  quick_stats_path: data/quick_stats.csv
  change_in_time_path: data/change_in_time.csv
  custom_metrics_path: data/custom_metrics.json
  portfolio_path: data/portfolio.json
  transactions_path: data/transactions
  leader_history_path: data/leader_history
  leader_stats_path: data/leader_stats.csv
  baseline_portfolio_path: data/baseline_portfolio.json
  baseline_transactions_path: data/baseline_transactions
  real_portfolio_path: data/real_portfolio.json
  real_transactions_path: data/real_transactions

cache:
  min_memory_mb: 100

predictor:
  current_input_path: data/current_input.pickle
